
recsToDo = [
    {'name':'Simon Atileh','work':'He worked very hard with his teams to build a machine learning model that can predict the liklihood of having a heart attack based on several factors as well as a machine learning model and application that can predict car purchase prices.', 'grade':'A', 'pronoun':'he'},
    {'name':'Rehan Bharwani', 'work':'He did a detailed graphical analysis with a partner to find a correlation between gas consumption in the UK and the level of CO2 emissions produced.', 'grade':'A', 'pronoun':'he'},
    {'name':'Jeevan Bindra', 'work':'He worked very hard on several projects with his teams such as creating a machine learning model predict the liklihood of a person having a stroke based on several factors as well as analyzing data to find a correlation between a countries GDP and overall happiness score. ', 'grade':'A', 'pronoun':'he'},
    {'name':'Jorge Diaz', 'work':'He did a wonderful job analzying and displaying charted data showing correlations found between confirmed covid cases and death.  Jorge also worked with a partner to build a machine learning model to predict a countries Gross National Product based on several factors. ', 'grade':'A', 'pronoun':'he'},
    {'name':'Nina Kannan', 'work':'She did a great job showing a graphical analysis of chocolate bars and the correlation of their cocoa percentage and their overall rating and also worked with a team to build a machine learning model to predict heart disease in humans based off of several factors. ', 'grade':'A', 'pronoun':'she'},
    {'name':'Katherine Liew', 'work':'She did a great job using charts to show a correlation between unemployment rate and poluation within a given country.  She also worked hard with a team to create a machine learning model and interface that can predict the cut of a diamond based on 9 factors.  ', 'grade':'A', 'pronoun':'she'},
    {'name':'Chenjia Liu (Ricardo)', 'work':'He built an app and machine learning model that can predict home prices based on 11 factors. He showed understanding of the machine learning models and syntax but I would like to see him work with his fellow classmates a bit more instead of focusing on solo work. ', 'grade':'B', 'pronoun':'he'}, # Not as much participation
    {'name':'Yicheng Lu (Sean)', 'work':'He had a great understandings of all concepts covered and put a great amount of effort into all of the projects we worked in.  He worked with another student to create an interactive application and mahcine model that can predict the Gross National Product of a country based on 7 factors. ', 'grade':'A', 'pronoun':'he'},
    {'name':'ZhuoRan Ma (Charlotte)', 'work':'', 'grade':'C', 'pronoun':'she'},  #only turned in 2 assignments
    {'name':'Aarna Nair', 'work':'She worked hard in this course and collaborated very well with her teammates.  She performed several very detailed data analysis and presented her findings and found correlation very clearly.  ', 'grade':'A', 'pronoun':'she'},
    {'name':'Jonathan Nolan', 'work':'He did a wonderful job, put forth a lot of effort in this course and collaborated very well with his team to create and app and machine learning model that can predict the liklihood of lung cancer based on 15 factors.', 'grade':'A', 'pronoun':'he'},
    {'name':'Ayan Panjwani', 'work':'Ayan did a wonderful job on all of his assignments and presentations.  He went above and beyond often incorporating chart types and concepts that we had not covered in class.  ', 'grade':'A', 'pronoun':'he'},
    {'name':'Anna Shukhter', 'work':'She did a great job analzying datasets and presenting her findings.  Anna also also worked with a team to build a machine learning model to predict heart disease in humans based off of several factors.', 'grade':'A', 'pronoun':'she'},
    {'name':'Rohan Tayur', 'work':'Rohan did a wonderful job on all of his assignments and never hesitated to ask questions to gain a deeper understanding of the material.  He graphically analyzed data to find a correlation between user reviews and critic reviews given on videogames.  He also worked with a team to create an interactive machine learning model to predict the quality of diamonds based on several factors.   ', 'grade':'A', 'pronoun':'he'},
    {'name':'Jiaqi Wang', 'work':'Jiaqi analyzed a dataset to find a correlation between university rankings and their locations throughout the world.  ', 'grade':'A', 'pronoun':'she'},
    {'name':'Yuhao Wang', 'work':'He worked with his team to do a detailed analysis on the mot common factors that lead to lung cancer. ', 'grade':'B', 'pronoun':'he'},
    {'name':'Xianjie Yang', 'work':'', 'grade':'F', 'pronoun':'he'},
    {'name':'Jiaming Zhang', 'work':'', 'grade':'F', 'pronoun':'she'},
    ]